org.gradle.jvmargs=-Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.parallel = true
org.gradle.caching = true


minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=industrialsorcerygreg
mod_name=IndustrialSorceryGreg
mod_license=GNU AGPL 3.0
mod_url=test
mod_issue_tracker =
mod_version=0.1.0
mod_group_id=com.zircky
mod_authors=Zircky
mod_description=

